/**
 * Type definitions for the AI Outreach & Cover Letter Generator feature.
 *
 * Covers: generation request → Gemini response → stored draft → API response.
 */

// ---------------------------------------------------------------------------
// Request types
// ---------------------------------------------------------------------------

/**
 * Request to generate outreach documents from a previous resume analysis.
 */
export interface OutreachGenerationRequest {
  /** UUID of the resume analysis to base the outreach on */
  resumeAnalysisId: string;
  /** Authenticated user's ID */
  userId: string;
  /** Optional additional context the user wants to include */
  additionalContext?: string;
  /** Optional recruiter or hiring manager name */
  recipientName?: string;
  /** Optional specific company details not in the JD (recent news, etc.) */
  companyNotes?: string;
}

// ---------------------------------------------------------------------------
// Gemini response types
// ---------------------------------------------------------------------------

/**
 * A generated cover letter from Gemini.
 */
export interface GeneratedCoverLetter {
  /** Email subject line (6–10 words) */
  subject: string;
  /** Full cover letter body (200–250 words) */
  body: string;
  /** Actual word count of the body */
  wordCount: number;
  /** Specific details referenced from the company/JD */
  personalizedElements: string[];
}

/**
 * A generated cold outreach message from Gemini.
 */
export interface GeneratedOutreach {
  /** LinkedIn/email subject line (4–8 words) */
  subject: string;
  /** Full outreach message body (60–80 words) */
  body: string;
  /** Actual word count of the body */
  wordCount: number;
  /** Specific details referenced */
  personalizedElements: string[];
}

/**
 * Metadata about the generation context.
 */
export interface OutreachMetadata {
  /** Target company name */
  targetCompany: string;
  /** Target role title */
  targetRole: string;
  /** Skills from the resume that were emphasized */
  keySkillsHighlighted: string[];
  /** Brief note on tone choices made */
  toneNotes: string;
}

/**
 * Complete generation result returned by Gemini.
 */
export interface OutreachGenerationResult {
  /** The generated cover letter */
  coverLetter: GeneratedCoverLetter;
  /** The generated outreach message */
  outreachMessage: GeneratedOutreach;
  /** Metadata about what was personalized */
  metadata: OutreachMetadata;
}

// ---------------------------------------------------------------------------
// Draft status
// ---------------------------------------------------------------------------

/**
 * Status of an outreach draft.
 * - `draft`: freshly generated by AI, unedited
 * - `edited`: user has made inline changes
 * - `finalized`: user has marked it as ready to send
 */
export type DraftStatus = 'draft' | 'edited' | 'finalized';

// ---------------------------------------------------------------------------
// Stored / API response types
// ---------------------------------------------------------------------------

/**
 * An outreach draft as stored in PostgreSQL.
 */
export interface StoredOutreachDraft {
  /** UUID primary key */
  id: string;
  /** User who owns this draft */
  userId: string;
  /** Reference to the resume analysis this was based on */
  resumeAnalysisId: string;
  /** Job description used for generation */
  jobDescription: string;
  /** The generated cover letter (may be user-edited) */
  coverLetter: GeneratedCoverLetter;
  /** The generated outreach message (may be user-edited) */
  outreachMessage: GeneratedOutreach;
  /** Generation metadata */
  metadata: OutreachMetadata;
  /** Current draft status */
  status: DraftStatus;
  /** How many times this draft has been regenerated */
  version: number;
  /** When the draft was first created */
  createdAt: Date;
  /** When the draft was last updated */
  updatedAt: Date;
}

/**
 * Payload for updating an existing draft (user inline edits).
 */
export interface OutreachDraftUpdate {
  /** Updated cover letter body (optional) */
  coverLetterBody?: string;
  /** Updated cover letter subject (optional) */
  coverLetterSubject?: string;
  /** Updated outreach message body (optional) */
  outreachMessageBody?: string;
  /** Updated outreach message subject (optional) */
  outreachMessageSubject?: string;
  /** Updated status (optional) */
  status?: DraftStatus;
}

/**
 * API response envelope for outreach operations.
 */
export interface OutreachResponse {
  success: boolean;
  data?: StoredOutreachDraft;
  error?: string;
}

/**
 * API response for listing multiple drafts.
 */
export interface OutreachListResponse {
  success: boolean;
  data: StoredOutreachDraft[];
  meta: {
    total: number;
  };
}
